included:
  - Template
excluded:
  - Pods
  - Project/R.generated.swift
  
opt_in_rules:
  - all
  
disabled_rules:
  - trailing_whitespace
  - explicit_acl
  - anyobject_protocol
  - inert_defer
  - unused_capture_list
  - explicit_type_interface
  - discouraged_optional_collection
  - explicit_top_level_acl

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 800

large_tuple:
   - 3
   - 4
   
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 30
    error: 35
  excluded: iPhone # excluded via string
reporter: "xcode"
